[build]
builder = "dockerfile"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[env]
PORT = "8000"
PYTHONPATH = "/app"